In [1]:
import numpy as np
import math

In [7]:
#1.method1
t = 0
I = 0
lam = 7
S = []
T = 10
def lam_t(x):
    return 3+4/(x+1)

U = np.random.uniform(0, 1)
t = t - math.log(U)/lam
while(t <= T):
    U = np.random.uniform(0, 1)
    if U <= lam_t(t)/lam:
        I = I+1
        S.append(t)
    U = np.random.uniform(0, 1)
    t = t - math.log(U)/lam

print("發生事件的時間", S)
print("總次數",I)

發生事件的時間 [0.012420703825578572, 0.050432910110329854, 0.13641663901321585, 0.25984312628262834, 0.3610318939065796, 0.7442903067488176, 1.278850049005222, 1.3050857548019925, 1.4671227556732047, 1.7842085441634454, 1.895861223913581, 2.1952375946438707, 2.626257545743834, 2.7723564142166337, 2.7854969738246456, 2.9519224737150345, 3.3030569465555177, 3.3263394332193603, 3.490759052089016, 4.056393072009629, 4.422891966810518, 4.424019805448973, 5.065640379428279, 5.36928793766456, 5.515806767681972, 5.546731780400562, 5.815284657204931, 5.978941664632323, 6.149118795048681, 6.5378516460841505, 8.091579824534728, 8.336686177751458, 9.041077656043816, 9.756408612655418]
總次數 34


In [3]:
#2.

y = []
y.append([])
y.append([])
y.append([])
for i in range(3):
    for j in range(1000):
        U = np.random.uniform(0, 1, 3)
        Y = -math.log(U[0])
        while(U[1] > math.exp(-pow(Y-1,2)/2)):
            U = np.random.uniform(0, 1, 3)
            Y = -math.log(U[0])
        X = Y
        if U[2] <= 1/2: Z = X
        else: Z = -X
        y[i].append(Z)
        
cor = [[1, 0.5/2, 0.5/3],
        [0.5/2, 1, 0.5/6],
        [0.5/3, 0.5/6, 1]]
L = np.linalg.cholesky(cor)
print(L)
W = np.dot(L, y)
#print(np.mean(W[0]), np.mean(W[0]), np.mean(W[1])) #check mean
#print(np.corrcoef(np.vstack((W[0],W[1],W[2])))) #check correlation
def normal(v):
    dx = 1
    area = 0
    y = 0
    for x in range( 0, 1000, dx):
        x = x/1000
        y = v*math.exp(-pow(v*x, 2)/2)/math.sqrt(2*math.pi)
        area = area + (y * (dx/1000))
    if x>=0: return min(area+0.5, 0.99999999)
    else: return max(area+0.5, 0.00000001)
X = []
X.append([])
X.append([])
X.append([])
for i in range(3):
    for j in range(1000):
        temp = -math.log(1-normal(W[i][j]))*(i+1)
        X[i].append(temp)
Z = np.vstack((X[0],X[1],X[2]))
print("mean = ", np.mean(X[0]), np.mean(X[1]), np.mean(X[2]))
print("var = ", np.var(X[0]), np.var(X[1]), np.var(X[2]))
print("cov = \n", np.cov(Z))
print("cor = \n", np.corrcoef(Z))

[[1.         0.         0.        ]
 [0.25       0.96824584 0.        ]
 [0.16666667 0.04303315 0.98507379]]
mean =  1.0126562674750244 2.0419890859166925 2.9971627350004364
var =  0.8664155602090786 3.909655301271375 9.100286200849617
cov = 
 [[0.86728284 0.2839983  0.37642707]
 [0.2839983  3.91356887 0.5495015 ]
 [0.37642707 0.5495015  9.1093956 ]]
cor = 
 [[1.         0.1541519  0.13392316]
 [0.1541519  1.         0.09203174]
 [0.13392316 0.09203174 1.        ]]
